project:
  type: website

website:
  title: "RUHi Tutorial Hub"
  navbar:
    left:
      - text: "FijiFISH"
        menu:
          - text: "01_Installation"
            href: 01_installation.qmd
          - text: "02_File Structure"
            href: 02_file-structure.qmd
          - text: "03_Registration"
            href: 03_registration.qmd
          - text: "04_Segmentation"
            href: 04_segmentation.qmd
          - text: "05_Quantification"
            href: 05_quantification.qmd
          - text: "06_Overlay"
            href: 06_overlay.qmd
          - text: "07_Single Round mFISH"
            href: 07_single-round-mfish.qmd
          - text: "08_Customization"
            href: 08_customization.qmd
      - text: "RUHi"
        menu:
          - text: "01_Installation"
            href: 01_installation.qmd
          - text: "02_File Setup"
            href: 02_file-setup.qmd
          - text: "03_Reading Files"
            href: 03_reading-files.qmd
          - text: "04_The mFISH Object"
            href: 04_mfish-object.qmd
          - text: "05_The goFISH App"
            href: 05_gofish-app.qmd
          - text: "06_Filtering Processing"
            href: 06_filtering-processing.qmd
          - text: "07_Dimensionality Reduction & Clustering"
            href: 07_dimred-clustering.qmd
          - text: "08_Visualization"
            href: 08_visualization.qmd
          - text: "09_Geographic Analysis"
            href: 09_geographic-analysis.qmd
          - text: "10_Bespoke Analysis"
            href: 10_bespoke-analysis.qmd
          - text: "11_Multi Section Analysis"
            href: 11_multi-section-analysis.qmd
