project:
  type: website

website:
  title: "🎣 mFISH Tutorial Hub 🎣"
  navbar:
    left:
      - text: "FijiFISH Tutorial"
        menu:
          - text: "Installing FijiFISH"
            href: 01_installation-fiji.qmd
          - text: "Image File Structure"
            href: 02_file-structure-fiji.qmd
          - text: "Registration"
            href: 03_registration.qmd
          - text: "Segmentation"
            href: 04_segmentation.qmd
          - text: "Quantification"
            href: 05_quantification.qmd
          - text: "Overlay"
            href: 06_overlay.qmd
      - text: "RUHi Tutorial"
        menu:
          - text: "Installing RUHi"
            href: 01_installation-ruhi.qmd
          - text: "CSV File Setup"
            href: 02_file-setup-ruhi.qmd
          - text: "Reading Files"
            href: 03_reading-files.qmd
          - text: "The mFISH Object"
            href: 04_mfish-object.qmd
          - text: "The goFISH App"
            href: 05_gofish-app.qmd
          - text: "Filtering & Processing"
            href: 06_filtering-processing.qmd
          - text: "Dimensionality Reduction & Clustering"
            href: 07_dimred-clustering.qmd
          - text: "Visualization"
            href: 08_visualization.qmd
          - text: "Geographic Analysis"
            href: 09_geographic-analysis.qmd

